### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by zamentur** [YunoHost-Apps/unattended_upgrades_ynh#7]
https://paste.yunohost.org/raw/mezowuhizi

**Comment by zamentur** [comment]
It's on an YunoHost 3.3 with armbian

**Comment by maniackcrudelis** [comment]
Ah armbian... Always something different than debian...

**Comment by maniackcrudelis** [comment]
Could you have a look to `/etc/apt` to see if there's a default config for unattended-upgrades ?

**Comment by maniackcrudelis** [comment]
Just tested on my raspi, I do not reproduce your error.
Feel free to reopen if you go back to this issue one day...

**Comment by benneti** [comment]
The file "/etc/apt/apt.conf.d/50unattended-upgrades" does not exist on armbian for me, too.
Maybe this could be handled a bit more gracefully.

sudo apt remove --purge unattended-upgrades
sudo apt install unattended-upgrades

restores the file (dpk-reconfigure does not want to restore a deleted config file)

**Comment by maniackcrudelis** [comment]
You mean, you did install unattended-upgrades a first time and the file was missing. You purged it and reinstall it and it was present !?

**Comment by benneti** [comment]
Basicallly. It seems like is installed by default on armbian, so I purged it and then reinstalled i.
This creates the file, as it would be in the package and is just removed on the image.

**Comment by maniackcrudelis** [comment]
Well ok...
It's quite interesting to have your feedback on that issue and especially that solution to fix it.
Though, I don't think it would be a good idea to implement such a solution into the package directly.
I'd rather prefer to keep that topic to inform whomever would have that issue about how to fix it. We can't know if it works again. Who knows with armbian...

**Comment by benneti** [comment]
If I had known that before I would have used plain debian on my server board :laughing: .
Yeah, I think it is fine to leave it to the user to fix it.
